groups: []

resources:
- name: example-app
  type: git
  source:
    branch: master
    uri: https://github.com/Kolbeckenstein/jHipsterExample.git

jobs:
- name: junit-tests
  plan:
  - get: example-app
    trigger: true
  - task: run-junit-tests
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: latest
      inputs:
      - name: example-app
      run:
        path: example-app/ci/test.sh
        #path: ls
        #args: [example-app/ci]
- name: run-app
  plan:
  - get: example-app
    passed:
      - junit-tests
    trigger: true
  - task: run-app
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: latest
      inputs:
      - name: example-app
      run:
        path: example-app/ci/run.sh